server:
  port: 8084

spring:
  application:
    name: artist-service
  r2dbc:
    url: r2dbc:postgresql://sonifoy-db:5432/artist_db
    username: sonifoy_user
    password: sonifoy_password

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
